### ISSUE TITLE
payment result on  new MercadoPagoCheckout.startPayment has zero information about order

### ISSUE THREAD

**Issue by bolds07** [mercadopago/px-android#1451]
According to the documentation:

https://www.mercadopago.com.br/developers/pt/api-docs/custom-checkout/create-payments/

payment entity is suposed to have a property `additional_info` where i could get from which items are being paid

but the `Payment` in this library has no such field....
I also checked the metadata field and there isn't any data about the items

on `onActivityResult` the payment returned into the intent has no information like `order_id` so if for any reason i decide to not put the `external_reference` i have absolutelly no way to guess what is that payment from

**Comment by zehemz** [comment]
@bolds07  you already know which items are being paid because you are creating the preference.
additional_info is not a parameter supported by our lib and is not documented in our api. 
Our checkout does not support all the features the api does, the same way we do not support orders either.
The CheckoutPreference you create contains all the info you need to know about payer info + items, etc.

**Comment by bolds07** [comment]
is someone being paid to develop this? if you tell me all guys are volunatires doing on their spare time i would tottally believe it because if those guys where in my class of introduction to developping you would fail

this api is really making me think to use anything else as a gateway

**Comment by zehemz** [comment]
We do our best trying to develop this project and we have open it for anyone that wants to use it. 

We accept collaborators in order to improve our experience and provide many ways to pay with a simple integration and more complicated ones.

Please, feel free giving us feedback with respect and if you think that we can improve in any way please let us know.
Regards.

**Comment by bolds07** [comment]
I will briefly resume some of the many bad apects of this api i found in 1 week using (or trying to), you might include in your backlog or not... but if mercado pago does want to get markert share quality is one very important factor to consider, not just marketing.
Some of the aspects i will mention might not be from the scope of this github but you can redirect to the responsibles for that or just ignore as you wish.

1- the size: it's inadmissible that a single feature api has a such large size.
You can tell whatever you want to try to guilt picasso. but your api is a payment api, whatever image you handle in it, is such tiny detail that even if you had the worst perfomance api in the world, probably user wouldn't realize it... but having a large one is the first thing people will see.
I also noticed you import com.mercadolibre.android:ui. which import fresco... so you are including 2 different graphic apis for no reason.
Ignoring the size of support lib (which probably most people import) this api should not exceed 1MB.
no other of my apis do that and many of them handle tasks more complex like, retrofit, firebase, etc

2-Don't use onactivityresult to return data: there is no reason you need an activity context to do your work and using this interface you are forcing developper to always start your checkout from an activity, in my case i just wanted to checkout from a dialog... but i had a nightmare finding an elegant way...
To have a simple listener to your interface would easily solve this problem... any class which implements this listener can handle the checkout response, even a background thread.

3-LET USER IDENTIFY HIMSELF: i found the craziest thing ever the fact that I NEED TO INFORM THE DATA FROM THE USER, the user himself should do it. What if the user gives me an e-mail that is different from the e-mail he uses for mercado pago? he wouldn't be able to user his mp credits, or saved cards to pay for the purchase. During the checkout you always ask name and identification from user, you should include e-mail also

the whole preference->order->payment flow is irrational: i honestly can comprehend why you need to have user information to create a preference, and if you chose to do WHY DO YOU LET USER PAY TWICE?
so lets say user clicks on buy-> software creates a preference for that user and items-> user is directed through checkout... for some reason payment is processing but user thinks there was an error, he presses buy again and repeat the proccess...
some time later he realizes he has two identical orders.
this can be avoided from software side, but you are forcing everybody who uses the api to do that, what could be simple done from the api process side once...
either a preference can't be paid twice, or a preference hasn't a user into it.

less images PLEASE -> each app will use only one mercadopago key to process checkout and you said before the payment methods description come from the server... their images should also come!
if the account i'm using is from brazil, and user will only be allowed to chose from payment methods available in brazil its pointless to have many logos from falabella, bcp, bbva... etc etc etc.
Even is the same app is available world wide, the mp account it belongs will be the same, so all users from that specific app will se the same payment methods images, doesn't matter where they are from...
considering you have logos from most banks from south america, each app only shows maximum 10% of them they could be easily be loaded from web... or somehow splited by locale


i think the whole api concept here was focused on design, the animation are smooth, this whole carnival of images might be for make user feel confortable
but is a payment api. again focus is security from user data, mitigation of purchase errors and size.

**Comment by zehemz** [comment]
Can't agree more.
User login, lazy image loading and simplified checkout experiences (like you say, modal) are part of the scope we want to work this year.
For historical design matters this checkout had too many client side responsibilities and is too configurable (more than we like nowadays, from colors, custom views, payment plugin adons and so on). Did you know that you can place your own fragments inside our checkout with customized fragments?

Regarding lazy image loading I agree its overkilling to have all of them for certain countries, but also is serving for free resources too. Anyway we will do it as soon as our brand new backend api serve them.

Since last 6 months our focus was on make our public api stable and coherent (client side), documented and we also added many UX features, without removing most common features our users want.

Hopefuly what do you spect from our lib is what we also want, but maintaining compatibility and adding new features is too and it will take some time.

Regarding merdadolibre ui lib I agree is a tradeoff, we can't remove picasso nor fresco due tech difficulties, but we will do it.

Feel free to make us a PR to contribute with this project. Our goal is to democratice payments in latam and let the developers choose wich fees and to whom are them directed.
