### ISSUE TITLE
will be this api ever optmized?

### ISSUE THREAD

**Issue by bolds07** [mercadopago/px-android#1674]
> @bolds07 this issue has been fixed on 4.6.2
> [4.6.1...4.6.2](https://github.com/mercadopago/px-android/compare/4.6.1...4.6.2)
> 
> Anyway, we recommend you to use 4.7.2 that is a newer version.
> 
> Soon in 4.8.0 we will reduce the size of our pngs one of the things you ask for.

i'm using the 4.10.0 and still the resources are wayyyyyyyyyyy to big

my app without mercadopago api apk 5.0MB
my app with mercadopago api 10.8MB

just twice the size... so if you costumers are just huge app companies with apps larger than 20MB it may be no difference...

if you really want to create a universal api for any developper you are way going in the wrong way...

imagine i create an app for taking photos and charge the users 1 dolar per photo, the app itself would be just few kbs for loading the camera... and 5MB of mercadopago lib it makes NOOOOO SENSE

you are talking about SOUTH AMERICA more than 70% of devices out there are low end devices and have no spare memory and disk to all this stuff my app is 5MB and when i force uses to update i get lots of complain because some people need to delete photos and other apps in order to be able to update

so i'm 90% sure i will delete this api from my app i just want to ask one last time:

IS THERE ANY REAL ESTIMATIVE TO REMOVE THE GARBAGE OUT OF THIS API? 

You have a thousand drawables that are ABSOLUTELLY POINTLESS. who was the genius that had the idea to put every logo from every bank in south america in an api?

just to give you a short hint, the probabillity of someone who has an bank account in brazil (and sees brazilian banks) also have a bank account in colombia (and then see colombian logos) is about 1%

so for every single user that uses this payment system, he will just see 10% of the logos you put into the lib, but he will be forced to load all of them... would be smarter to simple load them from the server...

**Comment by zehemz** [comment]
@bolds07 We will but we have some work to do first. I won't provide you a date yet but it will be soon.

Take in count that if all the resources comes from server we should also provide static storage for that and that involves a cost for us because of the huge traffic we receive, we are an open source project and we should commit to give long term support for those things.

Regards.

**Comment by jsotuyod** [comment]
@bolds07 regardless of the changes already in backlog @zehemz already mentioned, I'd like to give you some ideas that would help you a lot right now regardless of what version of PX you are using.

Firstly, given the context you provide (which is absolutely right), you should strongly consider generating split APKs, at least for different screen densities. That way, instead of having a universal APK with all assets for all screen densities, you get fine grained versions for each device. Lower-end devices (with less available storage and worst screens) will get significantly smaller APKs.

This way, the overall impact of using PX will go down significantly.

For more info you can check the Android Gradle Plugin DSL:

http://google.github.io/android-gradle-dsl/current/com.android.build.gradle.internal.dsl.Splits.html#com.android.build.gradle.internal.dsl.Splits:density

Also, you should be using Proguard if you aren't already. The size impact won't be as dramatic, but most likely than not, you are using a single use-case among those supported by PX, so being able to reduce the final DEX is always positive.

For reference, the Mercado Pago application makes extensive usage of APK splits and Proguard ships not only PX, but also:
* top up cellphone recharge in 3 countries
* drivers to support 3 different mPOS hardwares
* transport cards recharge in 2 countries
* QR payments
* P2P payments
* home, settings, activities, and much more

and it currently sits at ~16MB for xhdpi devices.

We have ongoing efforts to keep driving that number down, but certainly PX is not the 30% of the app's current weight.

**Comment by bolds07** [comment]
> @bolds07 We will but we have some work to do first. I won't provide you a date yet but it will be soon.
> 
> Take in count that if all the resources comes from server we should also provide static storage for that and that involves a cost for us because of the huge traffic we receive, we are an open source project and we should commit to give long term support for those things.
> 
> Regards.

you already do this, there is no difference.... if i get the preference id and instead of use the android-checkout-px open the link at the users browser it will load all the rousources from the cloud anyaway... this "cost of huge traffic" is a super lame excuse i bet not even 10% of the traffic related to mercado pago come from this api and if you simple provide

keep in mind that google billing api does everything you do on 40kb only and it doesn't require the developper to have a backeend, all the billing information is processed on the fly

paypal does similar with an api size of 600kb
